import os, sqlite3, json
from werkzeug.security import generate_password_hash
from app import DB
from reader_migrations import ensure_reader_schema

os.makedirs(os.path.dirname(DB),exist_ok=True)
if os.path.exists(DB): os.remove(DB)
c=sqlite3.connect(DB)
c.executescript('''
create table users(id integer primary key,username text unique not null,password_hash text not null,display_name text not null,role text not null default 'student',active integer not null default 1,must_change_password integer not null default 1);
create table lessons(id integer primary key,title text,unit text,position integer,question text,proposition text,counter_proposition text,restatement text,reading text,animation_slug text);
create table definitions(id integer primary key,lesson_id integer,term text,definition text);
create table proofs(id integer primary key,lesson_id integer,position integer,title text,evidence text,major_premise text,minor_premise text,conclusion text);
create table questions(id integer primary key,lesson_id integer,prompt text,options_json text,correct_answer text,explanation text);
create table lesson_progress(user_id integer,lesson_id integer,attempts integer default 0,best_score integer,completed integer default 0,updated_at text,primary key(user_id,lesson_id));
create table attempts(id integer primary key,user_id integer,lesson_id integer,score integer,created_at text);
create table books(id integer primary key,title text,author text,description text,source_note text,is_full_text integer not null default 0,source_url text default '',reading_level text default '');
create table chapters(id integer primary key,book_id integer,position integer,title text,content text);
create table reading_progress(user_id integer,chapter_id integer,completed integer,last_read_at text,primary key(user_id,chapter_id));
create table reading_questions(id integer primary key,chapter_id integer not null,prompt text not null,options_json text not null,correct_answer text not null,explanation text default '');
create table reading_attempts(id integer primary key,user_id integer not null,chapter_id integer not null,score integer not null,created_at text not null);
create table bookmarks(user_id integer not null,chapter_id integer not null,created_at text not null,primary key(user_id,chapter_id));
create table assignments(id integer primary key,title text,description text);
create table assignment_questions(id integer primary key,assignment_id integer,prompt text,options_json text,correct_answer text,explanation text);
create table assignment_attempts(id integer primary key,user_id integer,assignment_id integer,score integer,created_at text);
create table skill_scores(user_id integer,skill text,score integer,primary key(user_id,skill));
''')
c.execute('insert into users(username,password_hash,display_name,role,active,must_change_password) values(?,?,?,?,1,1)',('admin',generate_password_hash('admin'),'Administrator','admin'))

lessons=[
('Definitions Before Debate','Logic Foundations',1,'Why must debaters agree on definitions before arguing?','A sound debate requires stable, shared definitions of its important terms.','Debaters can understand each other without explicitly defining terms.','Therefore, shared definitions reduce ambiguity and make it possible to test whether each argument actually addresses the same proposition.','A debate can appear logical while the speakers quietly use one word in different senses. Classical argument begins by determining what important terms mean.','definitions'),
('Validity and Soundness','Logic Foundations',2,'Can a valid argument still have a false conclusion in practice?','A good argument requires both valid logical form and adequately supported premises.','If an argument has a valid form, no further examination is needed.','Therefore, logical form and premise quality must be evaluated separately.','Validity asks whether the conclusion follows if the premises are true. Soundness additionally asks whether the premises are in fact true.','syllogism'),
('Limited Rendering','Physics & Reality',3,'Does the physical universe behave in a manner consistent with limited rendering?','The universe exhibits physical behaviors that can be compared with limited rendering.','Quantum mechanics does not require or uniquely imply computational rendering.','Therefore, limited rendering can be used as a philosophical analogy for some physical behavior, but the analogy does not establish that reality is simulated.','Compare a computational system that resolves detail when interaction requires it with quantum measurement, information constraints, and decoherence. Keep observation separate from interpretation.','limited_rendering'),
('Reality as Information','Physics & Reality',4,'Is information more fundamental than matter?','Physical reality may be fundamentally describable in informational terms.','Information may only be a useful description of physical systems rather than their underlying substance.','Therefore, information is central to modern physics, but whether information is ontologically fundamental remains a philosophical question.','Quantum information and black-hole thermodynamics make information physically important. The philosophical question is whether information merely describes reality or constitutes reality.','information'),
('Mathematical Universe','Physics & Reality',5,'Is mathematics merely a description of reality, or part of its structure?','The deep mathematical regularity of nature suggests mathematical structure is fundamental to physical reality.','Mathematics may work because humans developed it to model regularities found in nature.','Therefore, mathematics clearly captures real regularities, while the stronger claim that reality itself is mathematics remains open.','Physics repeatedly uses mathematical structures to make successful predictions. The debate concerns what this success means philosophically.','mathematical_universe'),
('Simulation Hypothesis','Physics & Reality',6,'Does current evidence justify believing that our universe is a simulation?','Simulation is a philosophically possible interpretation of reality but is not established by current physics.','A hypothesis without unique falsifiable predictions should not be treated as an established scientific explanation.','Therefore, simulation theory is useful for debate about knowledge, probability, and explanation, but present physics does not demonstrate that we inhabit a simulation.','This lesson separates logical possibility, statistical arguments, physical analogy, and scientific evidence.','simulation')]
for L in lessons:c.execute('insert into lessons(title,unit,position,question,proposition,counter_proposition,restatement,reading,animation_slug) values(?,?,?,?,?,?,?,?,?)',L)

def add_defs(lid, items):
    for t,d in items:c.execute('insert into definitions(lesson_id,term,definition) values(?,?,?)',(lid,t,d))
def add_proofs(lid, items):
    for i,(t,e,maj,minr,con) in enumerate(items,1):c.execute('insert into proofs(lesson_id,position,title,evidence,major_premise,minor_premise,conclusion) values(?,?,?,?,?,?,?)',(lid,i,t,e,maj,minr,con))
def add_q(lid,prompt,opts,correct,ex):c.execute('insert into questions(lesson_id,prompt,options_json,correct_answer,explanation) values(?,?,?,?,?)',(lid,prompt,json.dumps(opts),correct,ex))

add_defs(1,[('Definition','A statement that fixes the meaning of a term for the argument.'),('Equivocation','Using the same word in different senses within an argument.'),('Proposition','A statement presented for examination as true or false.'),('Premise','A statement offered as support for a conclusion.'),('Conclusion','A statement claimed to follow from premises.')])
add_proofs(1,[('Shared Meaning','Reasoning can only be compared when key terms remain stable.','Arguments require stable meanings to test whether premises support conclusions.','Agreed definitions stabilize the meanings of important terms.','Therefore, agreed definitions make arguments easier to test.'),('Equivocation Control','Changing a term mid-argument can make an invalid inference appear persuasive.','Arguments that change a term’s meaning risk equivocation.','Unfixed definitions allow meanings to change unnoticed.','Therefore, fixed definitions reduce equivocation.'),('Disagreement Location','Definitions help reveal whether people disagree about facts, inference, or language.','A useful debate identifies the actual point of disagreement.','Shared definitions remove many merely verbal disagreements.','Therefore, shared definitions help locate the real disagreement.')])
add_q(1,'What is equivocation?',['Changing the meaning of a term during an argument','Providing evidence','Restating a proposition','Using a counterexample'],'Changing the meaning of a term during an argument','Equivocation occurs when a key term shifts meaning during reasoning.')
add_q(1,'Agreement on a definition means the debaters must agree with the proposition.',['True','False'],'False','Debaters can share definitions while disagreeing completely about the proposition.')
add_q(1,'Which should normally come first?',['Definitions','Conclusion','Personal opinion','Winning'],'Definitions','Shared terms are established before evaluating the argument built from them.')

add_defs(2,[('Validity','The conclusion follows from the premises if the premises are assumed true.'),('Soundness','An argument is valid and its premises are true or adequately justified.'),('Syllogism','A deductive argument commonly expressed using a major premise, minor premise, and conclusion.'),('Counterexample','An instance that shows a universal claim is false.')])
add_proofs(2,[('Logical Form','A conclusion can only be deductively guaranteed when the form preserves truth.','Deductive arguments require a truth-preserving form.','Validity tests whether an argument has a truth-preserving form.','Therefore, validity is required for a sound deductive argument.'),('Premise Quality','A perfectly valid inference can start from false premises.','A sound argument requires true or justified premises.','Validity alone does not establish that premises are true.','Therefore, validity alone does not establish soundness.'),('Two Tests','Separating form from evidence makes reasoning easier to diagnose.','Arguments can fail because of form or because of premises.','Validity tests form while soundness includes premise truth.','Therefore, both tests are necessary to diagnose an argument.')])
add_q(2,'A valid argument must have true premises.',['True','False'],'False','Validity concerns form. Soundness requires both validity and true premises.')
add_q(2,'Which asks whether the conclusion follows from the premises?',['Validity','Popularity','Confidence','Authority'],'Validity','Validity evaluates logical consequence.')
add_q(2,'A sound deductive argument is:',['Valid with true premises','Popular with experts','Long and detailed','Impossible to question'],'Valid with true premises','Soundness combines valid form with true premises.')

add_defs(3,[('Reality','The physical world that produces the observations we experience.'),('Rendering','Producing a definite representation from an underlying state or instructions.'),('Limited Rendering','The proposed idea that a system resolves only the detail required for relevant interaction rather than maintaining all possible detail in the same way at all times.'),('Observer','For this lesson, a physical system involved in an interaction or measurement; not necessarily a conscious person.'),('Measurement','A physical interaction that produces a measurable result.'),('Superposition','A quantum state represented as a combination of possible measurement outcomes.'),('Decoherence','Loss of observable quantum interference through interaction with an environment.'),('Evidence','An observation that raises or lowers reasonable support for a proposition.'),('Consistency','The ability of an observation and a proposition to both be true without contradiction.')])
add_proofs(3,[('Quantum Measurement','Quantum theory represents systems with states that can include multiple possible measurement outcomes, while a measurement yields a definite recorded outcome.','Systems that resolve definite information during interaction resemble limited rendering.','Quantum measurement produces definite recorded outcomes during interaction.','Therefore, quantum measurement can resemble limited rendering.'),('Information Constraints','Physics limits causal information transfer; locally, usable signals do not propagate faster than light.','Limited information systems have constraints on information transfer or access.','The universe has constraints on information transfer or access.','Therefore, the universe has a characteristic consistent with a limited information system.'),('Decoherence','Interactions with the environment suppress observable interference and make alternatives behave classically for practical purposes.','If accessible state information depends on interaction, interaction helps determine what information becomes observable.','Decoherence changes what quantum interference remains observably accessible through environmental interaction.','Therefore, interaction helps determine what quantum information remains observably accessible.')])
add_q(3,'In this lesson, “observer” must mean a conscious human.',['True','False'],'False','Quantum measurement does not require a conscious human observer.')
add_q(3,'“Consistent with limited rendering” means “proves simulation theory.”',['True','False'],'False','Consistency is weaker than proof; multiple explanations can fit the same observation.')
add_q(3,'Which statement is an interpretation rather than a direct observation?',['The detector recorded one outcome','The universe uses rendering','An interference pattern was recorded','A signal arrived at a detector'],'The universe uses rendering','“Rendering” is a proposed interpretation or analogy, not the direct measurement itself.')

add_defs(4,[('Information','Distinguishable state or structure that can in principle be represented or transmitted.'),('Entropy','A physical quantity related to the number of microscopic states compatible with a macroscopic state.'),('Black-hole entropy','Entropy associated with a black hole, proportional to horizon area in semiclassical physics.'),('Holographic principle','Theoretical idea that information describing a region may admit an equivalent description on a lower-dimensional boundary.')])
add_proofs(4,[('Quantum Information','Quantum states can encode information and obey physical constraints on information processing.','What is indispensable to the behavior of fundamental physical systems may reveal fundamental structure.','Information is indispensable to describing quantum systems.','Therefore, information may reveal fundamental physical structure.'),('Black-hole Entropy','Black-hole thermodynamics ties entropy to horizon area.','If information-related quantities are fixed by physical geometry, information is deeply connected to physical structure.','Black-hole entropy is fixed by horizon geometry.','Therefore, information is deeply connected to physical structure.'),('Holographic Descriptions','Some gravitational theories permit equivalent descriptions with different dimensionality.','If the same physics has a complete lower-dimensional description, apparent volume need not be the only fundamental description.','Holographic dualities provide lower-dimensional descriptions of higher-dimensional physics.','Therefore, apparent volume need not be the only fundamental description.')])
add_q(4,'Does the holographic principle by itself prove that the universe is a computer simulation?',['Yes','No'],'No','A lower-dimensional or informational description is not the same claim as an external computer simulation.')
add_q(4,'Black-hole entropy is related to:',['Horizon area','Favorite color','Human attention','Language'],'Horizon area','In semiclassical black-hole thermodynamics entropy scales with horizon area.')
add_q(4,'Information being useful in physics proves it is the only substance that exists.',['True','False'],'False','Usefulness or centrality does not by itself settle an ontological claim.')

add_defs(5,[('Mathematical model','A mathematical structure used to represent or predict aspects of a system.'),('Prediction','A consequence stated before the relevant observation is known.'),('Mathematical realism','The philosophical view that mathematical entities or structures exist independently of human thought.'),('Description','A representation of a system that need not be identical to the system itself.')])
add_proofs(5,[('Prediction','Mathematical models can make precise predictions about physical systems.','A structure that repeatedly predicts unknown behavior captures real regularities.','Mathematics repeatedly predicts previously unmeasured physical behavior.','Therefore, mathematics captures real physical regularities.'),('Universality','Physical mathematical relationships do not depend on which human language describes them.','Relationships independent of local human convention are not merely local linguistic conventions.','Physical mathematical relationships persist across languages and cultures.','Therefore, those relationships are not merely local linguistic conventions.'),('Compression','Compact equations can represent enormous classes of physical behavior.','A representation that compresses many observations into stable relations captures structure shared by those observations.','Physical equations compress many observations into stable relations.','Therefore, physical equations capture shared structure in those observations.')])
add_q(5,'Successful mathematical prediction proves that reality literally is mathematics.',['True','False'],'False','Prediction supports the claim that mathematics captures structure; the stronger ontological claim requires additional argument.')
add_q(5,'A mathematical model is best described as:',['A representation of aspects of a system','The same thing as the system in every respect','A personal belief','A fallacy'],'A representation of aspects of a system','Models represent selected structure and need not be identical to what they model.')
add_q(5,'Which is the stronger claim?',['Mathematics describes physical regularities','Reality literally is a mathematical object'],'Reality literally is a mathematical object','The second is an ontological claim beyond the descriptive success of mathematics.')

add_defs(6,[('Simulation','A representation or implementation of one system produced by another according to rules.'),('Simulation hypothesis','The proposition that experienced reality is implemented by a more fundamental system.'),('Falsifiability','The possibility that an observation could count against a hypothesis.'),('Unique prediction','A prediction that distinguishes one hypothesis from relevant alternatives.'),('Underdetermination','A situation in which the available evidence is compatible with multiple explanations.')])
add_proofs(6,[('Logical Possibility','Nothing in ordinary experience obviously demonstrates that simulation is logically impossible.','A hypothesis not containing a contradiction may be logically possible.','The simulation hypothesis contains no obvious formal contradiction merely by being stated.','Therefore, the simulation hypothesis may be logically possible.'),('Observer-Number Argument','If conscious simulated observers existed in vastly greater numbers than non-simulated observers, some sampling arguments could favor simulated observers.','If one class overwhelmingly dominates a relevant random population, a random member is probably from that class.','Simulated observers could dominate the relevant population if vast conscious simulations are possible and common.','Therefore, under those assumptions, a random observer could probably be simulated.'),('Scientific Limitation','Most proposed simulation clues are compatible with non-simulation physics too.','Evidence compatible with several explanations does not uniquely establish one explanation.','Current proposed simulation clues are compatible with several explanations.','Therefore, current clues do not uniquely establish simulation.')])
add_q(6,'A hypothesis can be logically possible without being scientifically established.',['True','False'],'True','Possibility is much weaker than empirical confirmation.')
add_q(6,'What most weakens a scientific claim that can explain every possible outcome?',['Lack of falsifiability','Good grammar','Popularity','Length'],'Lack of falsifiability','If no possible outcome counts against a claim, empirical testing cannot discriminate it effectively.')
add_q(6,'If the same evidence fits several explanations, this is called:',['Underdetermination','Equivocation','Ad hominem','Deduction'],'Underdetermination','Underdetermination occurs when evidence does not select a unique explanation.')

# Book reader: include short public-domain selections + instructions for full-text import.
books=[('The Categories','Aristotle','A classical foundation for categories, predication, definition, and disciplined reasoning.','Public-domain source; this starter contains selected excerpts and an import guide for full texts.'),('A Treatise Concerning the Principles of Human Knowledge','George Berkeley','Primary-source reading on ideas, perception, matter, and what it means for something to exist.','Public-domain source; selected excerpts included.'),('An Enquiry Concerning Human Understanding','David Hume','Primary-source reading on causation, evidence, probability, induction, and skepticism.','Public-domain source; selected excerpts included.')]
for b in books:c.execute('insert into books(title,author,description,source_note) values(?,?,?,?)',b)
chapters=[
(1,1,'On Things Said Without Combination','Among things that are said without combination, each signifies either substance, quantity, quality, relation, where, when, position, having, doing, or being affected.\n\nASSIGNMENT PROMPT: Identify which terms in a modern physics debate are categories, properties, relations, or actions. Then explain which require explicit definitions before debate.'),
(1,2,'On Substance and Predication','A central task in the Categories is distinguishing what is said of a subject from what is present in a subject.\n\nASSIGNMENT PROMPT: Take the proposition “Reality is informational.” Identify the subject, what is being predicated of it, and what must be clarified before the proposition can be evaluated.'),
(2,1,'Ideas and Perception','Berkeley asks the reader to examine what is immediately present to the mind in perception and what is inferred beyond those perceptions.\n\nASSIGNMENT PROMPT: Separate three observations from three interpretations in a discussion of the double-slit experiment.'),
(2,2,'What Does It Mean To Exist?','Berkeley’s project challenges an easy assumption that our idea of physical substance is straightforward. Whether one accepts his conclusion or not, his method forces careful definition of object, perception, idea, and existence.\n\nASSIGNMENT PROMPT: Define “exists independently of observation” in a way that both sides of a debate could use.'),
(3,1,'Cause and Effect','Hume examines how knowledge of cause and effect extends beyond what is immediately observed, and asks what justifies such inferences.\n\nASSIGNMENT PROMPT: Give one observation, one causal inference, and one possible alternative explanation from a physics example.'),
(3,2,'Skeptical Discipline','Hume’s skeptical method asks how far evidence actually carries us rather than how far we would like it to carry us.\n\nASSIGNMENT PROMPT: For simulation theory, write the strongest conclusion justified by the evidence and then a stronger conclusion that the evidence does not yet justify.')]
for ch in chapters:c.execute('insert into chapters(book_id,position,title,content) values(?,?,?,?)',ch)
ensure_reader_schema(c)

assignments=[('Logic Foundations Mastery','Self-graded review of definitions, propositions, validity, soundness, and fallacies.'),('Physics vs. Interpretation','Practice separating observations from philosophical interpretations.'),('Final Dialectic','Demonstrate that you can analyze an unfamiliar proposition from both sides.')]
for a in assignments:c.execute('insert into assignments(title,description) values(?,?)',a)
def aq(a,p,opts,correct,ex):c.execute('insert into assignment_questions(assignment_id,prompt,options_json,correct_answer,explanation) values(?,?,?,?,?)',(a,p,json.dumps(opts),correct,ex))
aq(1,'What must be stable before a formal debate begins?',['Definitions','Emotions','Winner','Conclusion'],'Definitions','Definitions prevent the same term from drifting between meanings.')
aq(1,'A valid syllogism with a false premise is necessarily sound.',['True','False'],'False','Soundness requires both validity and true premises.')
aq(1,'Attacking a weaker version of an opponent’s argument is:',['Straw man','Deduction','Steelman','Measurement'],'Straw man','A straw man substitutes a weaker position for the opponent’s actual position.')
aq(1,'What is the strongest charitable reconstruction of an opponent called?',['Steelman','Red herring','Equivocation','Appeal to popularity'],'Steelman','Steelmanning means reconstructing an opponent’s strongest reasonable case.')
aq(2,'“A detector recorded one event” is primarily:',['Observation','Simulation proof','Metaphysical conclusion','Fallacy'],'Observation','It reports what was measured rather than what ultimate interpretation must be true.')
aq(2,'“The detector result proves the universe renders only what we observe” is primarily:',['Interpretation','Raw measurement','Definition','Instrument reading'],'Interpretation','It adds a philosophical explanation beyond the recorded observation.')
aq(2,'If several theories predict the same observation, the evidence is:',['Underdetermined','Automatically false','A syllogism','An ad hominem'],'Underdetermined','The evidence does not uniquely select among those theories.')
aq(3,'Unfamiliar proposition: “Every event has a predetermined cause.” What should you do first?',['Define key terms','Choose a side permanently','Attack the speaker','Search for a red herring'],'Define key terms','The meaning of “event,” “predetermined,” and “cause” must be stabilized first.')
aq(3,'After building the strongest argument for the proposition, what is the next best exercise?',['Build the strongest counterargument','Repeat it louder','Ignore objections','Change definitions'],'Build the strongest counterargument','Position switching tests understanding and guards against confirmation bias.')
aq(3,'What question best tests scientific falsifiability?',['What evidence could show this claim is wrong?','Who believes it?','Is it exciting?','Can I make it sound persuasive?'],'What evidence could show this claim is wrong?','A falsifiable claim exposes itself to possible counterevidence.')

c.commit(); c.close(); print('Initialized',DB,'with admin/admin')
